PostgresDB:
  user: 'samson'
  password: 'qwerty'
  host: 'db'
  port: '5432'
  dbname: 'postgres'
  sslmode: 'disable'
  maxconns: '30'

Server:
  bindAddr: '0.0.0.0:8000'
  readTimeout: '10'
  writeTimeout: '10'
  idleTimeout: '5'
